#cloud-config
autoinstall:
  version: 1
  locale: en_GB.UTF-8
  keyboard:
   layout: us
   variant: ''
  refresh-installer:
    update: yes
  source:
    id: ubuntu-desktop
    search_drivers: true
  storage:
    config:
    - id: install-disk
      type: disk
      match:
        size: largest
      ptable: gpt
      wipe: superblock
      preserve: false
      name: ''
      grub_device: true
    
    - id: efi
      type: partition
      device: install-disk
      size: 1048576
      offset: 1048576
      wipe: superblock
      number: 1
      preserve: false
      flag: bios_grub
    
    - id: boot
      type: partition
      device: install-disk
      size: 1G
      wipe: superblock
      number: 2
      preserve: false
    
    - id: system
      type: partition
      device: install-disk
      size: 40G
      wipe: superblock
      number: 3
      preserve: false
    
    - id: swap
      type: partition
      device: install-disk
      size: 10G
      wipe: superblock
      flag: swap
      number: 4
      preserve: false
    
    - id: home
      type: partition
      device: install-disk
      size: -1
      wipe: superblock
      number: 5
      preserve: false
    
    - id: boot_fs
      type: format
      volume: boot
      fstype: ext4
      label: boot
      preserve: false
   
    - id: system_fs
      type: format
      volume: system
      fstype: ext4
      label: system
      preserve: false
    
    - id: swap_fs
      type: format
      volume: swap
      fstype: swap
      preserve: false
    
    - id: home_fs
      type: format
      volume: home
      fstype: ext4
      label: home
      preserve: false
    
    - id: boot-mount
      type: mount
      device: boot_fs
      path: /boot
   
    - id: system-mount
      type: mount
      device: system_fs
      path: /
    
    - id: swap-mount
      type: mount
      device: swap_fs
      path: ''
    
    - id: home-mount
      type: mount
      device: home_fs
      path: /home


  swap:
    size: 0
  identity: 
    hostname: ubuntu-desktop-matu
    username: felix
    password: $6$cDc4q9xz5pivJi28$g1FG/WjKkvlUwWd4n7qMr50rskuIKAfHeYy63RxcMvo.oajtAodLktx8cb1DneEX44J0wOSXM6mLpndtdBoHx.
  codecs:
    install: true
  drivers:
    install: true
  oem:
    install: true
  updates: all
  shutdown: reboot
  timezone: Europe/Vienna
  user-data:
    users:
      - name: toor
        passwd: '$6$j02MKnqkw.R1Psvi$CFNTn0Fw3fI4PEQZI.vruMz/rotTe8YZ3Bf/JlDnRX0VSgG0mrVC1aUrzemJ0DdRZE8OU0/jT5DoYHokLKkWA/'
        groups: adm, lp, cdrom, sudo, dip, lpadmin, plugdev
        shell: /bin/bash
        lock_passwd: false
        
